server:
  port: 9099

mitocode:
  security:
    key: bWl0b2NvZGUtc2VjcmV0bWl0b2NvZGUtc2VjcmV0bWl0b2NvZGUtc2VjcmV0bWl0b2NvZGUtc2VjcmV0bWl0b2NvZGUtc2VjcmV0

# Mongo configuration
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/mitocode