server:
  port: ${CUSTOM.SERVER.PORT:9080}

#Spring cloud gateway router

spring:
  cloud:
    gateway:
      routes:
        - id: product-service-route
          uri: lb://product-service #ahí lo está haciendo con Eureka server, para hacerlo con el api gateway el balanceo, se pondría http://service-1.com, http://service-2.com
          predicates: 
            - Path=/api/product-service/**
          filters:
            - StripPrefix=2 # para que tome desde el segundo valor del Path
            - AddRequestParameter=flag,true
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/user-service/**
          filters:
            - StripPrefix=2
            - UserServiceFilter=MitocodeKey,MitocodeValue